"""Mapping scheme."""
from __future__ import annotations

MAP = {
    "id": {"initial", True},
    "uuid": {"initial", True},
    "product_id": {"initial", True},
    "user_id": {"initial", True},
    "serial_number": {"initial", True},
    "mac_address": {"initial", True},
    "name": {"initial", True},
    "locked": {"initial", True},
    "firmware_version": {"initial", True},
    "firmware_auto_upgrade": {"initial", True},
    "push_notifications": {"initial", True},
    "sim": {"initial", True},
    "push_notifications_level": {"initial", True},
    "test": {"initial", True},
    "iot_registered": {"initial", True},
    "mqtt_registered": {"initial", True},
    "pin_code": {"initial", True},
    "registered_at": {"initial", True},
    "online": {"initial", True},
    "app_settings": {"initial", True},
    "accessories": {"initial", True},
    "features": {"initial", True},
    "pending_radio_link_validation": {"initial", True},
    "mqtt_endpoint": {"initial", True},
    "mqtt_topics": {"initial", True},
    "warranty_registered": {"initial", True},
    "purchased_at": {"initial", True},
    "warranty_expires_at": {"initial", True},
    "setup_location": {"initial", True},
    "city": {"initial", True},
    "time_zone": {"initial", True},
    "lawn_size": {"initial", True},
    "lawn_perimeter": {"initial", True},
    "auto_schedule_settings": {"initial", True},
    "auto_schedule": {"initial", True},
    "distance_covered": {"initial", True},
    "mower_work_time": {"initial", True},
    "blade_work_time": {"initial", True},
    "blade_work_time_reset": {"initial", True},
    "blade_work_time_reset_at": {"initial", True},
    "battery_charge_cycles": {"initial", True},
    "battery_charge_cycles_reset": {"initial", True},
    "battery_charge_cycles_reset_at": {"initial", True},
    "messages_in": {"initial", True},
    "messages_out": {"initial", True},
    "raw_messages_in": {"initial", True},
    "raw_messages_out": {"initial", True},
    "created_at": {"initial", True},
    "updated_at": {"initial", True},
    "cfg": {
        "name": "configuration",
        "sub": {
            "id": {"name": "last_message_id"},
            "lg": {"name": "language"},
            "tm": {"name": "time"},
            "dt": {"name": "date"},
            "sc": {
                "name": "schedule",
                "sub": {
                    "m": {"name": "schedule_active"},
                    "p": {"name": "schedule_extension"},
                    "d": {"name": "schedule_primary"},
                    "dd": {"name": "schedule_secondary"},
                },
            },
            "cmd": {"name": "command"},
            "mz": {"name": "zone"},
            "mzv": {"name": "zone_indicator"},
            "rd": {"name": "raindelay"},
        },
    },
    "dat": {
        "name": "data",
        "sub": {
            "mac": {"name": "mac"},
            "fw": {"name": "firmware_version"},
            "bt": {
                "name": "battery",
                "sub": {
                    "t": {"name": "temperature"},
                    "v": {"name": "voltage"},
                    "p": {"name": "charge_percent"},
                    "nr": {"name": "charge_cycles"},
                    "c": {"name": "is_charging"},
                    "m": {"name": "m"},  # Naming?!
                },
            },
            "dmp": {"name": "accelerometer"},
            "st": {
                "name": "statistics",
                "sub": {
                    "b": {"name": "blade_on"},
                    "d": {"name": "distance"},
                    "wt": {"name": "time_mowing"},
                },
            },
            "ls": {"name": "status_code"},
            "le": {"name": "error_code"},
            "lz": {"name": "next_zone"},
            "rsi": {"name": "wifi_signal_strength"},
            "lk": {"name": "lk"},  # Naming?!
        },
    },
}

TIMESTAMPS = [
    "blade_work_time_reset_at",
    "created_at",
    "updated_at",
    "purchased_at",
    "registered_at",
    "warranty_expires_at",
]
