[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "pyworxcloud"
version = "5.0.0"
description = "Landroid cloud (Positec) API library"
authors = ["Malene Trab <malene@trab.dk>"]
documentation = "https://github.com/mtrab/pyworxcloud"
classifiers = [
    "Topic :: Software Development :: Libraries :: Python Modules"
]

license = "MIT"
readme = "README.md"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/mtrab/pyworxcloud/issues"

[tool.poetry.dependencies]
python = "^3.9"
urllib3 = ">=1.26.5"
requests = "^2.32.0"
awsiotsdk = ">=1.28.2,<1.30.0"
aiohttp = "^3.11.0"
tzdata = ">=2024.1"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.0"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
